;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        downcase-region
        electric-newline-and-maybe-indent
        helm-M-x
        helm-mini
        helm-show-kill-ring
        indent-for-tab-command
        js2-mode-toggle-element
        kill-region
        org-force-self-insert
        orgtbl-self-insert-command
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        helm-buffers-list
        helm-projectile-find-file
        orgtbl-hijacker-command-102
        ))
